### ISSUE TITLE
Icon categories for in-app preview

### ISSUE THREAD

**Issue by PDDStudio** [Pinbadge/pinbadge-android-theme#10]
Should I keep the default one by PaperBoard or are we going to use custom categories? If so, i need the list of categories and which icon should be placed into which category

**Comment by crutchcorn** [comment]
What are the default ones?

**Comment by PDDStudio** [comment]
@crutchcorn take a look at the preview tab in the latest apk-build

**Comment by crutchcorn** [comment]
Yeah, might as well keep them that for now. In the future, we might switch from GAMES to something else, but I can't think of anything

**Comment by PDDStudio** [comment]
Okay, the icons will be added to the specific categories once the appfilter is ready and up-to-date.
