### ISSUE TITLE
In-App / Icon Picker Categories

### ISSUE THREAD

**Issue by PDDStudio** [Pinbadge/pinbadge-android-theme#15]
We have to decide about the naming of the different categories we want to split the apps up inside the pinbadge app itself and in the icon picker (e.g for Nova Launcher)

@crutchcorn As we've already discussed we're going to use alphabetical order in the icon picker, but are there any other categories (e.g google/system apps etc..) we want to include for a better overview?

**Comment by crutchcorn** [comment]
Yup! I would like Google Apps, System Apps, and Maybe Browsers? I'm not entirely sure past those 2 categories. Any other ideas aside from them?

**Comment by PDDStudio** [comment]
I'm fine with this, I just might need a list of declarations which icons should be placed in which category, the same listing for the in-app preview, too?
