### ISSUE TITLE
Typo in icon name: Dialer

### ISSUE THREAD

**Issue by PDDStudio** [Pinbadge/pinbadge-android-theme#16]
The current icon's name is "dailer.png", but should be " dialer.png"

**Comment by crutchcorn** [comment]
... :| DId I really make that mistake?

**Comment by PDDStudio** [comment]
@crutchcorn, yeah :D I think this shouldn't be hard to fix so no worries ;)

**Comment by danielhickman** [comment]
This probably was me from MaterialOS. I have issues spelling things. XD

**Comment by crutchcorn** [comment]
No, this was for sure me - as nothing is based off of MaterialOS :|

**Comment by danielhickman** [comment]
Oh I thought my AI file with that filename was to blame ;)

**Comment by PDDStudio** [comment]
So, might there someone who'll fix the typo? :camel:
