### ISSUE TITLE
Changing Blurred Picture Background

### ISSUE THREAD

**Issue by crutchcorn** [Pinbadge/pinbadge-android-theme#17]
This should change every so often while using the app, and every time the user opens the app. In the end, it should look something like this: 

![pinbadge_i1](https://cloud.githubusercontent.com/assets/9100169/11265353/85652c32-8e50-11e5-8c7d-65143d07ae82.png)

**Comment by PDDStudio** [comment]
Once the other tasks are done I'll look into this :+1:

**Comment by danielhickman** [comment]
I need that Network! I never get full bars with Verizon! All jokes aside, do you have an image to put there?

**Comment by crutchcorn** [comment]
Is it possible @PDDStudio to steam images from Getty, Shutterstock, or Fotolia 
http://developers.gettyimages.com/en/
https://www.fotolia.com/Services/API
http://api.shutterstock.com/
Or any other free to use photo service (maybe even Google?) to get the images?

**Comment by loctauxphilippe** [comment]
flick's nice
it would be awesome to get g+ images!
or maybe our own pictures! :D

**Comment by PDDStudio** [comment]
@crutchcorn yeah it doesn't matter where to load the images from, the question is whether the user likes this feature or not, as because if you're not on a wireless network it will use cellular data to load the images

**Comment by danielhickman** [comment]
I rarely use the dashboard of any icon pack, so I say lets create only a few backgrouns like this and use them as wallpapers too.

**Comment by PDDStudio** [comment]
@danielhickman yep, maybe with a toggle to fetch images from external resources or something like that. However, are the images we're going to use already blurred by default or shall I add a 'blurred overlay' effect programmatically?
