### ISSUE TITLE
Add Play Store Link To Readme

### ISSUE THREAD

**Issue by prempalsingh** [Pinbadge/pinbadge-android-theme#22]
Thanks for those beautiful icons.
I couldn't find this on the Play Store. Has it been published yet?

**Comment by crutchcorn** [comment]
Not yet. WIth the amazing work of @PDDStudio, we are rebuilding the dashboard and then adding a few icons. A new beta should be out soon and then we will push our way to the play store!


I will leave this issue open until:
1) Published to play store 
2) README.md updated to include play store link

**Comment by prempalsingh** [comment]
Thanks for the quick response. Any chance of open sourcing the Android app as well?

**Comment by crutchcorn** [comment]
Anytime!

You'll be glad to know that not only is the app currently (and forever more) open sourced (check the dev branch), but when the dashboard is finished, @PDDStudio will be open sourcing his own and [some tools](https://github.com/PDDStudio/simple-request-parser) to use alongside when he releases.

**Comment by ploctaux** [comment]
You can also get the latest (old) build of Pinbadge here: https://pinbadge.github.io/pinbadge-android-theme
At your own risk :)
It may eat your cat :D
