### ISSUE TITLE
Client for android base?

### ISSUE THREAD

**Issue by PDDStudio** [Pinbadge/pinbadge-android-theme#3]
Paperboard or create from Scratch?
Any requirements? :camel:

**Comment by crutchcorn** [comment]
I will certainly be using paperboard, as I do not know Java development.

**Comment by PDDStudio** [comment]
@crutchcorn I'd start with the dashboard using Paperboard as base if this is okey? Or shall I wait for the first commit from your side?

**Comment by crutchcorn** [comment]
I'd love for you to! :D Thanks so much!
