### ISSUE TITLE
Application strings, colors, drawables and general layout required

### ISSUE THREAD

**Issue by PDDStudio** [Pinbadge/pinbadge-android-theme#4]
Topic should explain it so far.
Highest Priority would be the general layout of the application, and the strings/texts which should be used within the dashboard.

**Comment by crutchcorn** [comment]
I will consider this and make a mockup of the application. Don't worry, because I myself am not doing the coding - I will most likely not ask for Paperboard to change the look of the applications too much

**Comment by PDDStudio** [comment]
@crutchcorn There's no limitation for the Dashboard's UI, it can look however you want it to

**Comment by crutchcorn** [comment]
Sounds amazing! I'll take that into consideration when doing the mockup!

**Comment by PDDStudio** [comment]
I'll close this issue for now. In case of improvements or requests don't hesitate to reopen this issue again.
