### ISSUE TITLE
Muzei Support, Wallpaper section and included package request manager

### ISSUE THREAD

**Issue by PDDStudio** [Pinbadge/pinbadge-android-theme#5]
In theory they're implemented already (by default with Paperboard).
Now it's up to @crutchcorn wether those functionalities should be kept or removed.
Awaiting statement on how to continue with those.

**Comment by crutchcorn** [comment]
Muzei will be a no. Yes to wallpaper section (I will supply the wallpapers at another time - I need to select them), and yes to the package request manager (have the email be crutchcorn@gmail.com)

**Comment by PDDStudio** [comment]
Okey I'll set up the icon requests and temporary disable the wallpaper section. The muzei stuff woll be completely removed from the source.

**Comment by crutchcorn** [comment]
Thank you much!
