### ISSUE TITLE
Exported Drawables for Icons needed

### ISSUE THREAD

**Issue by PDDStudio** [Pinbadge/pinbadge-android-theme#6]
See the title. Actually I don't have AI, so I can't export them myself. Needs to be done by @crutchcorn :camel:

**Comment by crutchcorn** [comment]
By drawables, do you mean SVG files? Is it possible to do so with PNGs?

**Comment by PDDStudio** [comment]
PNG's are possible and recommend in 192x192

**Comment by crutchcorn** [comment]
Will do. Where do you want them?

**Comment by crutchcorn** [comment]
Just exported them to master/PNGs
