### ISSUE TITLE
Fix back button press event to quit the dashboard

### ISSUE THREAD

**Issue by PDDStudio** [Pinbadge/pinbadge-android-theme#7]
When not being in the 'Home' section pressing the back button won't quit the application. Will fix this later. @crutchcorn Should there be an dialog which asks for quitting the dashboard or should it quit it immediately when the back button is pressed?

**Comment by crutchcorn** [comment]
There should be a dialog asking if the user wants to quit the dashboard

**Comment by PDDStudio** [comment]
Okay, will add this then

**Comment by PDDStudio** [comment]
As discussed, the application is switching back to the home fragment after the first press, and then quits on an other backbutton press event.
